UNAUTH = "未認証"
VALIDATE_PROJECT_NAME = "プロジェクト名と開始月は必須です!"
VALIDATE_REDMINE_GITHUB_AUTH = 'Redmine or GitHubどちらかは認証してください!'
SECURE = 'HOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGE'
CIPHER = 'aes-256-cbc'


