require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RedmineKeysController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RedmineKey. As you add validations to RedmineKey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RedmineKeysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all redmine_keys as @redmine_keys" do
      redmine_key = RedmineKey.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:redmine_keys)).to eq([redmine_key])
    end
  end

  describe "GET #show" do
    it "assigns the requested redmine_key as @redmine_key" do
      redmine_key = RedmineKey.create! valid_attributes
      get :show, {:id => redmine_key.to_param}, valid_session
      expect(assigns(:redmine_key)).to eq(redmine_key)
    end
  end

  describe "GET #new" do
    it "assigns a new redmine_key as @redmine_key" do
      get :new, {}, valid_session
      expect(assigns(:redmine_key)).to be_a_new(RedmineKey)
    end
  end

  describe "GET #edit" do
    it "assigns the requested redmine_key as @redmine_key" do
      redmine_key = RedmineKey.create! valid_attributes
      get :edit, {:id => redmine_key.to_param}, valid_session
      expect(assigns(:redmine_key)).to eq(redmine_key)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RedmineKey" do
        expect {
          post :create, {:redmine_key => valid_attributes}, valid_session
        }.to change(RedmineKey, :count).by(1)
      end

      it "assigns a newly created redmine_key as @redmine_key" do
        post :create, {:redmine_key => valid_attributes}, valid_session
        expect(assigns(:redmine_key)).to be_a(RedmineKey)
        expect(assigns(:redmine_key)).to be_persisted
      end

      it "redirects to the created redmine_key" do
        post :create, {:redmine_key => valid_attributes}, valid_session
        expect(response).to redirect_to(RedmineKey.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved redmine_key as @redmine_key" do
        post :create, {:redmine_key => invalid_attributes}, valid_session
        expect(assigns(:redmine_key)).to be_a_new(RedmineKey)
      end

      it "re-renders the 'new' template" do
        post :create, {:redmine_key => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested redmine_key" do
        redmine_key = RedmineKey.create! valid_attributes
        put :update, {:id => redmine_key.to_param, :redmine_key => new_attributes}, valid_session
        redmine_key.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested redmine_key as @redmine_key" do
        redmine_key = RedmineKey.create! valid_attributes
        put :update, {:id => redmine_key.to_param, :redmine_key => valid_attributes}, valid_session
        expect(assigns(:redmine_key)).to eq(redmine_key)
      end

      it "redirects to the redmine_key" do
        redmine_key = RedmineKey.create! valid_attributes
        put :update, {:id => redmine_key.to_param, :redmine_key => valid_attributes}, valid_session
        expect(response).to redirect_to(redmine_key)
      end
    end

    context "with invalid params" do
      it "assigns the redmine_key as @redmine_key" do
        redmine_key = RedmineKey.create! valid_attributes
        put :update, {:id => redmine_key.to_param, :redmine_key => invalid_attributes}, valid_session
        expect(assigns(:redmine_key)).to eq(redmine_key)
      end

      it "re-renders the 'edit' template" do
        redmine_key = RedmineKey.create! valid_attributes
        put :update, {:id => redmine_key.to_param, :redmine_key => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested redmine_key" do
      redmine_key = RedmineKey.create! valid_attributes
      expect {
        delete :destroy, {:id => redmine_key.to_param}, valid_session
      }.to change(RedmineKey, :count).by(-1)
    end

    it "redirects to the redmine_keys list" do
      redmine_key = RedmineKey.create! valid_attributes
      delete :destroy, {:id => redmine_key.to_param}, valid_session
      expect(response).to redirect_to(redmine_keys_url)
    end
  end

end
